# -*- coding: utf-8 -*-

OK = 0

DB_ERROR = 4001

PARAM_ERROR = 4101

AUTHORIZATION_ERROR = 4201

UNKNOWN_ERROR = 4301

CODE_MSG_MAP = {
    OK: 'ok',
    DB_ERROR: 'DB_ERROR',
    PARAM_ERROR: 'PARAM_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    UNKNOWN_ERROR: "UNKNOWN_ERROR"
}
