version: '3'
services:
  db:
    image: mysql
    container_name: mysql_aws_saa
    ports:
      - "18801:3306"
      - "18802:33060"
    volumes:
      - "aws_saa_volume:/var/lib/mysql"
      - "aws_saa_volume:/tmp"
      - "aws_saa_volume:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
volumes:
  aws_saa_volume: 
