version: "3"
services:
  db:
    build: ./sql
    container_name: mysql_aws_saa
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_log:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      # - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
      - ${DB_PORT2}:33060

